name: Generate Changelog
on:
  push:
    branches:
      - master

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Changelog
        uses: release-drafter/release-drafter@v5
        with:
          token: ${{ secrets.ACTION_TOKEN }}
